<?php 
 $GLOBALS["dictionary"]["mks_CollectionConcepts"]=array (
  'table' => 'mks_collectionconcepts',
  'audited' => true,
  'inline_edit' => true,
  'duplicate_merge' => true,
  'fields' => 
  array (
    'id' => 
    array (
      'name' => 'id',
      'vname' => 'LBL_ID',
      'type' => 'id',
      'required' => true,
      'reportable' => true,
      'comment' => 'Unique identifier',
      'inline_edit' => false,
    ),
    'name' => 
    array (
      'name' => 'name',
      'vname' => 'LBL_NAME',
      'type' => 'name',
      'link' => true,
      'dbType' => 'varchar',
      'len' => 255,
      'unified_search' => true,
      'full_text_search' => 
      array (
        'boost' => 3,
      ),
      'required' => true,
      'importable' => 'required',
      'duplicate_merge' => 'enabled',
      'merge_filter' => 'selected',
    ),
    'date_entered' => 
    array (
      'name' => 'date_entered',
      'vname' => 'LBL_DATE_ENTERED',
      'type' => 'datetime',
      'group' => 'created_by_name',
      'comment' => 'Date record created',
      'enable_range_search' => true,
      'options' => 'date_range_search_dom',
      'inline_edit' => false,
    ),
    'date_modified' => 
    array (
      'name' => 'date_modified',
      'vname' => 'LBL_DATE_MODIFIED',
      'type' => 'datetime',
      'group' => 'modified_by_name',
      'comment' => 'Date record last modified',
      'enable_range_search' => true,
      'options' => 'date_range_search_dom',
      'inline_edit' => false,
    ),
    'modified_user_id' => 
    array (
      'name' => 'modified_user_id',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_MODIFIED',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'group' => 'modified_by_name',
      'dbType' => 'id',
      'reportable' => true,
      'comment' => 'User who last modified record',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'modified_by_name' => 
    array (
      'name' => 'modified_by_name',
      'vname' => 'LBL_MODIFIED_NAME',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'rname' => 'user_name',
      'table' => 'users',
      'id_name' => 'modified_user_id',
      'module' => 'Users',
      'link' => 'modified_user_link',
      'duplicate_merge' => 'disabled',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'created_by' => 
    array (
      'name' => 'created_by',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_CREATED',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'dbType' => 'id',
      'group' => 'created_by_name',
      'comment' => 'User who created record',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'created_by_name' => 
    array (
      'name' => 'created_by_name',
      'vname' => 'LBL_CREATED',
      'type' => 'relate',
      'reportable' => false,
      'link' => 'created_by_link',
      'rname' => 'user_name',
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'created_by',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
      'importable' => 'false',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'description' => 
    array (
      'name' => 'description',
      'vname' => 'LBL_DESCRIPTION',
      'type' => 'text',
      'comment' => 'Full text of the note',
      'rows' => 6,
      'cols' => 80,
    ),
    'deleted' => 
    array (
      'name' => 'deleted',
      'vname' => 'LBL_DELETED',
      'type' => 'bool',
      'default' => '0',
      'reportable' => false,
      'comment' => 'Record deletion indicator',
    ),
    'created_by_link' => 
    array (
      'name' => 'created_by_link',
      'type' => 'link',
      'relationship' => 'mks_collectionconcepts_created_by',
      'vname' => 'LBL_CREATED_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'modified_user_link' => 
    array (
      'name' => 'modified_user_link',
      'type' => 'link',
      'relationship' => 'mks_collectionconcepts_modified_user',
      'vname' => 'LBL_MODIFIED_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'assigned_user_id' => 
    array (
      'name' => 'assigned_user_id',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'vname' => 'LBL_ASSIGNED_TO_ID',
      'group' => 'assigned_user_name',
      'type' => 'relate',
      'table' => 'users',
      'module' => 'Users',
      'reportable' => true,
      'isnull' => 'false',
      'dbType' => 'id',
      'audited' => true,
      'comment' => 'User ID assigned to record',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_name' => 
    array (
      'name' => 'assigned_user_name',
      'link' => 'assigned_user_link',
      'vname' => 'LBL_ASSIGNED_TO_NAME',
      'rname' => 'user_name',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'assigned_user_id',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_link' => 
    array (
      'name' => 'assigned_user_link',
      'type' => 'link',
      'relationship' => 'mks_collectionconcepts_assigned_user',
      'vname' => 'LBL_ASSIGNED_TO_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
      'duplicate_merge' => 'enabled',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'table' => 'users',
    ),
    'SecurityGroups' => 
    array (
      'name' => 'SecurityGroups',
      'type' => 'link',
      'relationship' => 'securitygroups_mks_collectionconcepts',
      'module' => 'SecurityGroups',
      'bean_name' => 'SecurityGroup',
      'source' => 'non-db',
      'vname' => 'LBL_SECURITYGROUPS',
    ),
    'mks_registrationreceipts_mks_collectionconcepts_1' => 
    array (
      'name' => 'mks_registrationreceipts_mks_collectionconcepts_1',
      'type' => 'link',
      'relationship' => 'mks_registrationreceipts_mks_collectionconcepts_1',
      'source' => 'non-db',
      'module' => 'mks_RegistrationReceipts',
      'bean_name' => 'mks_RegistrationReceipts',
      'vname' => 'LBL_MKS_REGISTRATIONRECEIPTS_MKS_COLLECTIONCONCEPTS_1_FROM_MKS_REGISTRATIONRECEIPTS_TITLE',
      'id_name' => 'mks_regist10ebeceipts_ida',
    ),
    'mks_registrationreceipts_mks_collectionconcepts_1_name' => 
    array (
      'name' => 'mks_registrationreceipts_mks_collectionconcepts_1_name',
      'type' => 'relate',
      'source' => 'non-db',
      'vname' => 'LBL_MKS_REGISTRATIONRECEIPTS_MKS_COLLECTIONCONCEPTS_1_FROM_MKS_REGISTRATIONRECEIPTS_TITLE',
      'save' => true,
      'id_name' => 'mks_regist10ebeceipts_ida',
      'link' => 'mks_registrationreceipts_mks_collectionconcepts_1',
      'table' => 'mks_registrationreceipts',
      'module' => 'mks_RegistrationReceipts',
      'rname' => 'name',
    ),
    'mks_regist10ebeceipts_ida' => 
    array (
      'name' => 'mks_regist10ebeceipts_ida',
      'type' => 'link',
      'relationship' => 'mks_registrationreceipts_mks_collectionconcepts_1',
      'source' => 'non-db',
      'reportable' => false,
      'side' => 'right',
      'vname' => 'LBL_MKS_REGISTRATIONRECEIPTS_MKS_COLLECTIONCONCEPTS_1_FROM_MKS_COLLECTIONCONCEPTS_TITLE',
    ),
    'amount_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Importe',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'amount_c',
      'vname' => 'LBL_AMOUNT',
      'type' => 'currency',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '26',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => 6,
      'id' => 'mks_CollectionConceptsamount_c',
      'custom_module' => 'mks_CollectionConcepts',
    ),
    'surcharge_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Recargo',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'surcharge_c',
      'vname' => 'LBL_SURCHARGE',
      'type' => 'float',
      'massupdate' => '0',
      'default' => '0.00',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '18',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '2',
      'id' => 'mks_CollectionConceptssurcharge_c',
      'custom_module' => 'mks_CollectionConcepts',
    ),
    'discount_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Descuento',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'discount_c',
      'vname' => 'LBL_DISCOUNT',
      'type' => 'float',
      'massupdate' => '0',
      'default' => '0.00',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '18',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '2',
      'id' => 'mks_CollectionConceptsdiscount_c',
      'custom_module' => 'mks_CollectionConcepts',
    ),
    'subtotal_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'A pagar',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'subtotal_c',
      'vname' => 'LBL_SUBTOTAL',
      'type' => 'float',
      'massupdate' => '0',
      'default' => '0.00',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '18',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '2',
      'id' => 'mks_CollectionConceptssubtotal_c',
      'custom_module' => 'mks_CollectionConcepts',
    ),
    'total_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'A cobrar',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'total_c',
      'vname' => 'LBL_TOTAL',
      'type' => 'float',
      'massupdate' => '0',
      'default' => '0.00',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '18',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '2',
      'id' => 'mks_CollectionConceptstotal_c',
      'custom_module' => 'mks_CollectionConcepts',
    ),
    'mks_paymentconcepts_mks_collectionconcepts_1' => 
    array (
      'name' => 'mks_paymentconcepts_mks_collectionconcepts_1',
      'type' => 'link',
      'relationship' => 'mks_paymentconcepts_mks_collectionconcepts_1',
      'source' => 'non-db',
      'module' => 'mks_PaymentConcepts',
      'bean_name' => 'mks_PaymentConcepts',
      'vname' => 'LBL_MKS_PAYMENTCONCEPTS_MKS_COLLECTIONCONCEPTS_1_FROM_MKS_PAYMENTCONCEPTS_TITLE',
      'id_name' => 'mks_paymen2b29oncepts_ida',
    ),
    'mks_paymentconcepts_mks_collectionconcepts_1_name' => 
    array (
      'name' => 'mks_paymentconcepts_mks_collectionconcepts_1_name',
      'type' => 'relate',
      'source' => 'non-db',
      'vname' => 'LBL_MKS_PAYMENTCONCEPTS_MKS_COLLECTIONCONCEPTS_1_FROM_MKS_PAYMENTCONCEPTS_TITLE',
      'save' => true,
      'id_name' => 'mks_paymen2b29oncepts_ida',
      'link' => 'mks_paymentconcepts_mks_collectionconcepts_1',
      'table' => 'mks_paymentconcepts',
      'module' => 'mks_PaymentConcepts',
      'rname' => 'name',
    ),
    'mks_paymen2b29oncepts_ida' => 
    array (
      'name' => 'mks_paymen2b29oncepts_ida',
      'type' => 'link',
      'relationship' => 'mks_paymentconcepts_mks_collectionconcepts_1',
      'source' => 'non-db',
      'reportable' => false,
      'side' => 'right',
      'vname' => 'LBL_MKS_PAYMENTCONCEPTS_MKS_COLLECTIONCONCEPTS_1_FROM_MKS_COLLECTIONCONCEPTS_TITLE',
    ),
    'mks_collectionconcepts_mks_customplanfees_1' => 
    array (
      'name' => 'mks_collectionconcepts_mks_customplanfees_1',
      'type' => 'link',
      'relationship' => 'mks_collectionconcepts_mks_customplanfees_1',
      'source' => 'non-db',
      'module' => 'mks_CustomPlanFees',
      'bean_name' => 'mks_CustomPlanFees',
      'vname' => 'LBL_MKS_COLLECTIONCONCEPTS_MKS_CUSTOMPLANFEES_1_FROM_MKS_CUSTOMPLANFEES_TITLE',
      'id_name' => 'mks_collec6580lanfees_idb',
    ),
    'mks_collectionconcepts_mks_customplanfees_1_name' => 
    array (
      'name' => 'mks_collectionconcepts_mks_customplanfees_1_name',
      'type' => 'relate',
      'source' => 'non-db',
      'vname' => 'LBL_MKS_COLLECTIONCONCEPTS_MKS_CUSTOMPLANFEES_1_FROM_MKS_CUSTOMPLANFEES_TITLE',
      'save' => true,
      'id_name' => 'mks_collec6580lanfees_idb',
      'link' => 'mks_collectionconcepts_mks_customplanfees_1',
      'table' => 'mks_customplanfees',
      'module' => 'mks_CustomPlanFees',
      'rname' => 'name',
    ),
    'mks_collec6580lanfees_idb' => 
    array (
      'name' => 'mks_collec6580lanfees_idb',
      'type' => 'link',
      'relationship' => 'mks_collectionconcepts_mks_customplanfees_1',
      'source' => 'non-db',
      'reportable' => false,
      'side' => 'left',
      'vname' => 'LBL_MKS_COLLECTIONCONCEPTS_MKS_CUSTOMPLANFEES_1_FROM_MKS_CUSTOMPLANFEES_TITLE',
    ),
    'date_collection_concepts_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Fecha',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'date_collection_concepts_c',
      'vname' => 'LBL_DATE_COLLECTION_CONCEPTS',
      'type' => 'date',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
      'display_default' => 'now',
      'id' => 'mks_CollectionConceptsdate_collection_concepts_c',
      'custom_module' => 'mks_CollectionConcepts',
    ),
    'id_autoincrement_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => '#',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'id_autoincrement_c',
      'vname' => 'LBL_ID_AUTOINCREMENT',
      'type' => 'autoincrement',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 80,
      'size' => '20',
      'dbType' => 'varchar',
      'format' => '{}{}{}{}{00000001}{}{}',
      'start_number' => '00000001',
      'id' => 'mks_CollectionConceptsid_autoincrement_c',
      'custom_module' => 'mks_CollectionConcepts',
    ),
    'on_account_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'A Cuenta',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'on_account_c',
      'vname' => 'LBL_ON_ACCOUNT',
      'type' => 'float',
      'massupdate' => '0',
      'default' => '0.00',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '18',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '2',
      'id' => 'mks_CollectionConceptson_account_c',
      'custom_module' => 'mks_CollectionConcepts',
    ),
    'status_payment_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Estado',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'status_payment_c',
      'vname' => 'LBL_STATUS_PAYMENT',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => 'pending',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'status_payment_list',
      'studio' => 'visible',
      'dependency' => false,
      'id' => 'mks_CollectionConceptsstatus_payment_c',
      'custom_module' => 'mks_CollectionConcepts',
    ),
    'currency_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Moneda',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'currency_c',
      'vname' => 'LBL_CURRENCY_C',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => 'ARS',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'currency_list',
      'studio' => 'visible',
      'dependency' => false,
      'id' => 'mks_CollectionConceptscurrency_c',
      'custom_module' => 'mks_CollectionConcepts',
    ),
  ),
  'relationships' => 
  array (
    'mks_collectionconcepts_modified_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'mks_CollectionConcepts',
      'rhs_table' => 'mks_collectionconcepts',
      'rhs_key' => 'modified_user_id',
      'relationship_type' => 'one-to-many',
    ),
    'mks_collectionconcepts_created_by' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'mks_CollectionConcepts',
      'rhs_table' => 'mks_collectionconcepts',
      'rhs_key' => 'created_by',
      'relationship_type' => 'one-to-many',
    ),
    'mks_collectionconcepts_assigned_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'mks_CollectionConcepts',
      'rhs_table' => 'mks_collectionconcepts',
      'rhs_key' => 'assigned_user_id',
      'relationship_type' => 'one-to-many',
    ),
    'securitygroups_mks_collectionconcepts' => 
    array (
      'lhs_module' => 'SecurityGroups',
      'lhs_table' => 'securitygroups',
      'lhs_key' => 'id',
      'rhs_module' => 'mks_CollectionConcepts',
      'rhs_table' => 'mks_collectionconcepts',
      'rhs_key' => 'id',
      'relationship_type' => 'many-to-many',
      'join_table' => 'securitygroups_records',
      'join_key_lhs' => 'securitygroup_id',
      'join_key_rhs' => 'record_id',
      'relationship_role_column' => 'module',
      'relationship_role_column_value' => 'mks_CollectionConcepts',
    ),
  ),
  'optimistic_locking' => true,
  'unified_search' => true,
  'indices' => 
  array (
    'id' => 
    array (
      'name' => 'mks_collectionconceptspk',
      'type' => 'primary',
      'fields' => 
      array (
        0 => 'id',
      ),
    ),
  ),
  'templates' => 
  array (
    'security_groups' => 'security_groups',
    'assignable' => 'assignable',
    'basic' => 'basic',
  ),
  'custom_fields' => true,
);