<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2017 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */



// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'mks',
  'author' => 'MiKarpaSoft',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'CustomPaymentPlan',
  'published_date' => '2018-11-01 22:42:13',
  'type' => 'module',
  'version' => 1541112133,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'CustomPaymentPlan',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'mks_CustomPaymentPlan',
      'class' => 'mks_CustomPaymentPlan',
      'path' => 'modules/mks_CustomPaymentPlan/mks_CustomPaymentPlan.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'mks_CustomPlanFees',
      'class' => 'mks_CustomPlanFees',
      'path' => 'modules/mks_CustomPlanFees/mks_CustomPlanFees.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/mks_custompaymentplan_mks_registration_mks_Registration.php',
      'to_module' => 'mks_Registration',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/mks_custompaymentplan_mks_customplanfees_mks_CustomPaymentPlan.php',
      'to_module' => 'mks_CustomPaymentPlan',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/mks_custompaymentplan_mks_registrationMetaData.php',
    ),
    1 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/mks_custompaymentplan_mks_customplanfeesMetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/mks_CustomPaymentPlan',
      'to' => 'modules/mks_CustomPaymentPlan',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/mks_CustomPlanFees',
      'to' => 'modules/mks_CustomPlanFees',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/mks_CustomPaymentPlan.php',
      'to_module' => 'mks_CustomPaymentPlan',
      'language' => 'es_ES',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/mks_CustomPaymentPlan.php',
      'to_module' => 'mks_CustomPaymentPlan',
      'language' => 'en_us',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/mks_Registration.php',
      'to_module' => 'mks_Registration',
      'language' => 'es_ES',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/mks_Registration.php',
      'to_module' => 'mks_Registration',
      'language' => 'en_us',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/mks_CustomPlanFees.php',
      'to_module' => 'mks_CustomPlanFees',
      'language' => 'es_ES',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/mks_CustomPlanFees.php',
      'to_module' => 'mks_CustomPlanFees',
      'language' => 'en_us',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/mks_CustomPaymentPlan.php',
      'to_module' => 'mks_CustomPaymentPlan',
      'language' => 'es_ES',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/mks_CustomPaymentPlan.php',
      'to_module' => 'mks_CustomPaymentPlan',
      'language' => 'en_us',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/es_ES.lang.php',
      'to_module' => 'application',
      'language' => 'es_ES',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/mks_custompaymentplan_mks_registration_mks_CustomPaymentPlan.php',
      'to_module' => 'mks_CustomPaymentPlan',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/mks_custompaymentplan_mks_registration_mks_Registration.php',
      'to_module' => 'mks_Registration',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/mks_custompaymentplan_mks_customplanfees_mks_CustomPlanFees.php',
      'to_module' => 'mks_CustomPlanFees',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/mks_custompaymentplan_mks_customplanfees_mks_CustomPaymentPlan.php',
      'to_module' => 'mks_CustomPaymentPlan',
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    1 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
  ),
);