<?php 
 $GLOBALS["dictionary"]["mks_RegistrationReceipts"]=array (
  'table' => 'mks_registrationreceipts',
  'audited' => true,
  'inline_edit' => true,
  'duplicate_merge' => true,
  'fields' => 
  array (
    'id' => 
    array (
      'name' => 'id',
      'vname' => 'LBL_ID',
      'type' => 'id',
      'required' => true,
      'reportable' => true,
      'comment' => 'Unique identifier',
      'inline_edit' => false,
    ),
    'name' => 
    array (
      'name' => 'name',
      'vname' => 'LBL_NAME',
      'type' => 'name',
      'link' => true,
      'dbType' => 'varchar',
      'len' => 255,
      'unified_search' => true,
      'full_text_search' => 
      array (
        'boost' => 3,
      ),
      'required' => true,
      'importable' => 'required',
      'duplicate_merge' => 'enabled',
      'merge_filter' => 'selected',
    ),
    'date_entered' => 
    array (
      'name' => 'date_entered',
      'vname' => 'LBL_DATE_ENTERED',
      'type' => 'datetime',
      'group' => 'created_by_name',
      'comment' => 'Date record created',
      'enable_range_search' => true,
      'options' => 'date_range_search_dom',
      'inline_edit' => false,
    ),
    'date_modified' => 
    array (
      'name' => 'date_modified',
      'vname' => 'LBL_DATE_MODIFIED',
      'type' => 'datetime',
      'group' => 'modified_by_name',
      'comment' => 'Date record last modified',
      'enable_range_search' => true,
      'options' => 'date_range_search_dom',
      'inline_edit' => false,
    ),
    'modified_user_id' => 
    array (
      'name' => 'modified_user_id',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_MODIFIED',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'group' => 'modified_by_name',
      'dbType' => 'id',
      'reportable' => true,
      'comment' => 'User who last modified record',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'modified_by_name' => 
    array (
      'name' => 'modified_by_name',
      'vname' => 'LBL_MODIFIED_NAME',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'rname' => 'user_name',
      'table' => 'users',
      'id_name' => 'modified_user_id',
      'module' => 'Users',
      'link' => 'modified_user_link',
      'duplicate_merge' => 'disabled',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'created_by' => 
    array (
      'name' => 'created_by',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_CREATED',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'dbType' => 'id',
      'group' => 'created_by_name',
      'comment' => 'User who created record',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'created_by_name' => 
    array (
      'name' => 'created_by_name',
      'vname' => 'LBL_CREATED',
      'type' => 'relate',
      'reportable' => false,
      'link' => 'created_by_link',
      'rname' => 'user_name',
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'created_by',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
      'importable' => 'false',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'description' => 
    array (
      'name' => 'description',
      'vname' => 'LBL_DESCRIPTION',
      'type' => 'text',
      'comment' => 'Full text of the note',
      'rows' => 6,
      'cols' => 80,
    ),
    'deleted' => 
    array (
      'name' => 'deleted',
      'vname' => 'LBL_DELETED',
      'type' => 'bool',
      'default' => '0',
      'reportable' => false,
      'comment' => 'Record deletion indicator',
    ),
    'created_by_link' => 
    array (
      'name' => 'created_by_link',
      'type' => 'link',
      'relationship' => 'mks_registrationreceipts_created_by',
      'vname' => 'LBL_CREATED_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'modified_user_link' => 
    array (
      'name' => 'modified_user_link',
      'type' => 'link',
      'relationship' => 'mks_registrationreceipts_modified_user',
      'vname' => 'LBL_MODIFIED_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'assigned_user_id' => 
    array (
      'name' => 'assigned_user_id',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'vname' => 'LBL_ASSIGNED_TO_ID',
      'group' => 'assigned_user_name',
      'type' => 'relate',
      'table' => 'users',
      'module' => 'Users',
      'reportable' => true,
      'isnull' => 'false',
      'dbType' => 'id',
      'audited' => true,
      'comment' => 'User ID assigned to record',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_name' => 
    array (
      'name' => 'assigned_user_name',
      'link' => 'assigned_user_link',
      'vname' => 'LBL_ASSIGNED_TO_NAME',
      'rname' => 'user_name',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'assigned_user_id',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_link' => 
    array (
      'name' => 'assigned_user_link',
      'type' => 'link',
      'relationship' => 'mks_registrationreceipts_assigned_user',
      'vname' => 'LBL_ASSIGNED_TO_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
      'duplicate_merge' => 'enabled',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'table' => 'users',
    ),
    'SecurityGroups' => 
    array (
      'name' => 'SecurityGroups',
      'type' => 'link',
      'relationship' => 'securitygroups_mks_registrationreceipts',
      'module' => 'SecurityGroups',
      'bean_name' => 'SecurityGroup',
      'source' => 'non-db',
      'vname' => 'LBL_SECURITYGROUPS',
    ),
    'mks_registration_mks_registrationreceipts_1' => 
    array (
      'name' => 'mks_registration_mks_registrationreceipts_1',
      'type' => 'link',
      'relationship' => 'mks_registration_mks_registrationreceipts_1',
      'source' => 'non-db',
      'module' => 'mks_Registration',
      'bean_name' => 'mks_Registration',
      'vname' => 'LBL_MKS_REGISTRATION_MKS_REGISTRATIONRECEIPTS_1_FROM_MKS_REGISTRATION_TITLE',
      'id_name' => 'mks_registration_mks_registrationreceipts_1mks_registration_ida',
    ),
    'mks_registration_mks_registrationreceipts_1_name' => 
    array (
      'name' => 'mks_registration_mks_registrationreceipts_1_name',
      'type' => 'relate',
      'source' => 'non-db',
      'vname' => 'LBL_MKS_REGISTRATION_MKS_REGISTRATIONRECEIPTS_1_FROM_MKS_REGISTRATION_TITLE',
      'save' => true,
      'id_name' => 'mks_registration_mks_registrationreceipts_1mks_registration_ida',
      'link' => 'mks_registration_mks_registrationreceipts_1',
      'table' => 'mks_registration',
      'module' => 'mks_Registration',
      'rname' => 'document_name',
    ),
    'mks_registration_mks_registrationreceipts_1mks_registration_ida' => 
    array (
      'name' => 'mks_registration_mks_registrationreceipts_1mks_registration_ida',
      'type' => 'link',
      'relationship' => 'mks_registration_mks_registrationreceipts_1',
      'source' => 'non-db',
      'reportable' => false,
      'side' => 'right',
      'vname' => 'LBL_MKS_REGISTRATION_MKS_REGISTRATIONRECEIPTS_1_FROM_MKS_REGISTRATIONRECEIPTS_TITLE',
    ),
    'mks_registrationreceipts_mks_paymentscash_1' => 
    array (
      'name' => 'mks_registrationreceipts_mks_paymentscash_1',
      'type' => 'link',
      'relationship' => 'mks_registrationreceipts_mks_paymentscash_1',
      'source' => 'non-db',
      'module' => 'mks_PaymentsCash',
      'bean_name' => 'mks_PaymentsCash',
      'side' => 'right',
      'vname' => 'LBL_MKS_REGISTRATIONRECEIPTS_MKS_PAYMENTSCASH_1_FROM_MKS_PAYMENTSCASH_TITLE',
    ),
    'mks_registrationreceipts_mks_paymentstransfer_1' => 
    array (
      'name' => 'mks_registrationreceipts_mks_paymentstransfer_1',
      'type' => 'link',
      'relationship' => 'mks_registrationreceipts_mks_paymentstransfer_1',
      'source' => 'non-db',
      'module' => 'mks_PaymentsTransfer',
      'bean_name' => 'mks_PaymentsTransfer',
      'side' => 'right',
      'vname' => 'LBL_MKS_REGISTRATIONRECEIPTS_MKS_PAYMENTSTRANSFER_1_FROM_MKS_PAYMENTSTRANSFER_TITLE',
    ),
    'mks_registrationreceipts_mks_paymentscheck_1' => 
    array (
      'name' => 'mks_registrationreceipts_mks_paymentscheck_1',
      'type' => 'link',
      'relationship' => 'mks_registrationreceipts_mks_paymentscheck_1',
      'source' => 'non-db',
      'module' => 'mks_PaymentsCheck',
      'bean_name' => 'mks_PaymentsCheck',
      'side' => 'right',
      'vname' => 'LBL_MKS_REGISTRATIONRECEIPTS_MKS_PAYMENTSCHECK_1_FROM_MKS_PAYMENTSCHECK_TITLE',
    ),
    'mks_registrationreceipts_mks_paymentscard_1' => 
    array (
      'name' => 'mks_registrationreceipts_mks_paymentscard_1',
      'type' => 'link',
      'relationship' => 'mks_registrationreceipts_mks_paymentscard_1',
      'source' => 'non-db',
      'module' => 'mks_PaymentsCard',
      'bean_name' => 'mks_PaymentsCard',
      'side' => 'right',
      'vname' => 'LBL_MKS_REGISTRATIONRECEIPTS_MKS_PAYMENTSCARD_1_FROM_MKS_PAYMENTSCARD_TITLE',
    ),
    'mks_registrationreceipts_mks_collectionconcepts_1' => 
    array (
      'name' => 'mks_registrationreceipts_mks_collectionconcepts_1',
      'type' => 'link',
      'relationship' => 'mks_registrationreceipts_mks_collectionconcepts_1',
      'source' => 'non-db',
      'module' => 'mks_CollectionConcepts',
      'bean_name' => 'mks_CollectionConcepts',
      'side' => 'right',
      'vname' => 'LBL_MKS_REGISTRATIONRECEIPTS_MKS_COLLECTIONCONCEPTS_1_FROM_MKS_COLLECTIONCONCEPTS_TITLE',
    ),
    'mks_custompaymentplan_mks_registrationreceipts_1' => 
    array (
      'name' => 'mks_custompaymentplan_mks_registrationreceipts_1',
      'type' => 'link',
      'relationship' => 'mks_custompaymentplan_mks_registrationreceipts_1',
      'source' => 'non-db',
      'module' => 'mks_CustomPaymentPlan',
      'bean_name' => 'mks_CustomPaymentPlan',
      'vname' => 'LBL_MKS_CUSTOMPAYMENTPLAN_MKS_REGISTRATIONRECEIPTS_1_FROM_MKS_CUSTOMPAYMENTPLAN_TITLE',
      'id_name' => 'mks_custom8555entplan_ida',
    ),
    'mks_custompaymentplan_mks_registrationreceipts_1_name' => 
    array (
      'name' => 'mks_custompaymentplan_mks_registrationreceipts_1_name',
      'type' => 'relate',
      'source' => 'non-db',
      'vname' => 'LBL_MKS_CUSTOMPAYMENTPLAN_MKS_REGISTRATIONRECEIPTS_1_FROM_MKS_CUSTOMPAYMENTPLAN_TITLE',
      'save' => true,
      'id_name' => 'mks_custom8555entplan_ida',
      'link' => 'mks_custompaymentplan_mks_registrationreceipts_1',
      'table' => 'mks_custompaymentplan',
      'module' => 'mks_CustomPaymentPlan',
      'rname' => 'name',
    ),
    'mks_custom8555entplan_ida' => 
    array (
      'name' => 'mks_custom8555entplan_ida',
      'type' => 'link',
      'relationship' => 'mks_custompaymentplan_mks_registrationreceipts_1',
      'source' => 'non-db',
      'reportable' => false,
      'side' => 'right',
      'vname' => 'LBL_MKS_CUSTOMPAYMENTPLAN_MKS_REGISTRATIONRECEIPTS_1_FROM_MKS_REGISTRATIONRECEIPTS_TITLE',
    ),
    'id_autoincrement_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Número',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'id_autoincrement_c',
      'vname' => 'LBL_ID_AUTOINCREMENT_C',
      'type' => 'autoincrement',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 80,
      'size' => '20',
      'dbType' => 'varchar',
      'format' => '{}{}{}{}{00000000}{}{}',
      'start_number' => '00000001',
      'id' => 'mks_RegistrationReceiptsid_autoincrement_c',
      'custom_module' => 'mks_RegistrationReceipts',
    ),
    'total_effective_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Total en Efectivo',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'total_effective_c',
      'vname' => 'LBL_TOTAL_EFFECTIVE',
      'type' => 'float',
      'massupdate' => '0',
      'default' => '0.00',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '18',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '2',
      'id' => 'mks_RegistrationReceiptstotal_effective_c',
      'custom_module' => 'mks_RegistrationReceipts',
    ),
    'total_transfers_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Total en Transferencias',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'total_transfers_c',
      'vname' => 'LBL_TOTAL_TRANSFERS',
      'type' => 'float',
      'massupdate' => '0',
      'default' => '0.00',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '18',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '2',
      'id' => 'mks_RegistrationReceiptstotal_transfers_c',
      'custom_module' => 'mks_RegistrationReceipts',
    ),
    'total_checks_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Total en Cheques',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'total_checks_c',
      'vname' => 'LBL_TOTAL_CHECKS',
      'type' => 'float',
      'massupdate' => '0',
      'default' => '0.00',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '18',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '2',
      'id' => 'mks_RegistrationReceiptstotal_checks_c',
      'custom_module' => 'mks_RegistrationReceipts',
    ),
    'total_cards_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Total en Tarjetas',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'total_cards_c',
      'vname' => 'LBL_TOTAL_CARDS',
      'type' => 'float',
      'massupdate' => '0',
      'default' => '0.00',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '18',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '2',
      'id' => 'mks_RegistrationReceiptstotal_cards_c',
      'custom_module' => 'mks_RegistrationReceipts',
    ),
    'total_charge_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'TOTAL A COBRAR',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'total_charge_c',
      'vname' => 'LBL_TOTAL_CHARGE',
      'type' => 'float',
      'massupdate' => '0',
      'default' => '0.00',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '18',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '2',
      'id' => 'mks_RegistrationReceiptstotal_charge_c',
      'custom_module' => 'mks_RegistrationReceipts',
    ),
    'total_amount_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Total Importe',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'total_amount_c',
      'vname' => 'LBL_TOTAL_AMOUNT',
      'type' => 'float',
      'massupdate' => '0',
      'default' => '0.00',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '18',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '2',
      'id' => 'mks_RegistrationReceiptstotal_amount_c',
      'custom_module' => 'mks_RegistrationReceipts',
    ),
    'status_registration_receipts_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Estado',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'status_registration_receipts_c',
      'vname' => 'LBL_STATUS_REGISTRATION_RECEIPTS',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => 'draft',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'status_registration_receipts_list',
      'studio' => 'visible',
      'dependency' => false,
      'id' => 'mks_RegistrationReceiptsstatus_registration_receipts_c',
      'custom_module' => 'mks_RegistrationReceipts',
    ),
    'tmp_reg_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'ID Tmp',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'tmp_reg_c',
      'vname' => 'LBL_TMP_REG',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => 'Variable temporal usada en LH',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '36',
      'size' => '20',
      'id' => 'mks_RegistrationReceiptstmp_reg_c',
      'custom_module' => 'mks_RegistrationReceipts',
    ),
    'balance_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Balance',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'balance_c',
      'vname' => 'LBL_BALANCE',
      'type' => 'float',
      'massupdate' => '0',
      'default' => '0.00',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '18',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '2',
      'id' => 'mks_RegistrationReceiptsbalance_c',
      'custom_module' => 'mks_RegistrationReceipts',
    ),
    'date_receipts_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Fecha',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'date_receipts_c',
      'vname' => 'LBL_DATE_RECEIPTS',
      'type' => 'date',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
      'display_default' => 'now',
      'id' => 'mks_RegistrationReceiptsdate_receipts_c',
      'custom_module' => 'mks_RegistrationReceipts',
    ),
    'payment_date_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Fecha de Pago',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'payment_date_c',
      'vname' => 'LBL_PAYMENT_DATE_C',
      'type' => 'datetimecombo',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
      'dbType' => 'datetime',
      'id' => 'mks_RegistrationReceiptspayment_date_c',
      'custom_module' => 'mks_RegistrationReceipts',
    ),
    'total_discount_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Total Descuento(Cobranza)',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'total_discount_c',
      'vname' => 'LBL_TOTAL_DISCOUNT',
      'type' => 'float',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '18',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '2',
      'id' => 'mks_RegistrationReceiptstotal_discount_c',
      'custom_module' => 'mks_RegistrationReceipts',
    ),
    'type_rr_c' => 
    array (
      'inline_edit' => '',
      'labelValue' => 'Tipo',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'type_rr_c',
      'vname' => 'LBL_TYPE_RR',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'false',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'type_rr_list',
      'studio' => 'visible',
      'dependency' => NULL,
      'id' => 'mks_RegistrationReceiptstype_rr_c',
      'custom_module' => 'mks_RegistrationReceipts',
    ),
    'address_contact_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Domicilio del Alumno',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'address_contact_c',
      'vname' => 'LBL_ADDRESS_CONTACT',
      'type' => 'text',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '4',
      'cols' => '20',
      'id' => 'mks_RegistrationReceiptsaddress_contact_c',
      'custom_module' => 'mks_RegistrationReceipts',
    ),
    'telephone_contact_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Tel Alumno.',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'telephone_contact_c',
      'vname' => 'LBL_TELEPHONE_CONTACT',
      'type' => 'phone',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'dbType' => 'varchar',
      'id' => 'mks_RegistrationReceiptstelephone_contact_c',
      'custom_module' => 'mks_RegistrationReceipts',
    ),
    'next_expiration_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Prox Venc.',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'next_expiration_c',
      'vname' => 'LBL_NEXT_EXPIRATION',
      'type' => 'date',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
      'id' => 'mks_RegistrationReceiptsnext_expiration_c',
      'custom_module' => 'mks_RegistrationReceipts',
    ),
    'amount_in_letters_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Monto en Letras',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'amount_in_letters_c',
      'vname' => 'LBL_AMOUNT_IN_LETTERS',
      'type' => 'text',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '4',
      'cols' => '20',
      'id' => 'mks_RegistrationReceiptsamount_in_letters_c',
      'custom_module' => 'mks_RegistrationReceipts',
    ),
    'consolidated_concepts_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Consolidado de Conceptos',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'consolidated_concepts_c',
      'vname' => 'LBL_CONSOLIDATED_CONCEPTS',
      'type' => 'text',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '4',
      'cols' => '20',
      'id' => 'mks_RegistrationReceiptsconsolidated_concepts_c',
      'custom_module' => 'mks_RegistrationReceipts',
    ),
    'id_autoincrement_moron_a_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'id autoincrement moron a',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'id_autoincrement_moron_a_c',
      'vname' => 'LBL_ID_AUTOINCREMENT_MORON_A',
      'type' => 'autoincrement',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 80,
      'size' => '20',
      'dbType' => 'varchar',
      'format' => '{}{}{}{}{00000001}{}{}',
      'start_number' => '00000001',
      'id' => 'mks_RegistrationReceiptsid_autoincrement_moron_a_c',
      'custom_module' => 'mks_RegistrationReceipts',
    ),
    'id_autoincrement_moron_x_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'id autoincrement moron x',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'id_autoincrement_moron_x_c',
      'vname' => 'LBL_ID_AUTOINCREMENT_MORON_X',
      'type' => 'autoincrement',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 80,
      'size' => '20',
      'dbType' => 'varchar',
      'format' => '{}{}{}{}{00000000}{}{}',
      'start_number' => '00000001',
      'id' => 'mks_RegistrationReceiptsid_autoincrement_moron_x_c',
      'custom_module' => 'mks_RegistrationReceipts',
    ),
    'id_autoincrement_congreso_a_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'id autoincrement congreso a',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'id_autoincrement_congreso_a_c',
      'vname' => 'LBL_ID_AUTOINCREMENT_CONGRESO_A',
      'type' => 'autoincrement',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 80,
      'size' => '20',
      'dbType' => 'varchar',
      'format' => '{}{}{}{}{00000000}{}{}',
      'start_number' => '00000001',
      'id' => 'mks_RegistrationReceiptsid_autoincrement_congreso_a_c',
      'custom_module' => 'mks_RegistrationReceipts',
    ),
    'id_autoincrement_congreso_x_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'id autoincrement congreso x',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'id_autoincrement_congreso_x_c',
      'vname' => 'LBL_ID_AUTOINCREMENT_CONGRESO_X',
      'type' => 'autoincrement',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 80,
      'size' => '20',
      'dbType' => 'varchar',
      'format' => '{}{}{}{}{00000000}{}{}',
      'start_number' => '00000001',
      'id' => 'mks_RegistrationReceiptsid_autoincrement_congreso_x_c',
      'custom_module' => 'mks_RegistrationReceipts',
    ),
    'total_letters_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Total en letras',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'total_letters_c',
      'vname' => 'LBL_TOTAL_LETTERS',
      'type' => 'text',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '4',
      'cols' => '20',
      'id' => 'mks_RegistrationReceiptstotal_letters_c',
      'custom_module' => 'mks_RegistrationReceipts',
    ),
    'consolided_concept_values_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Consolidado Valores',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'consolided_concept_values_c',
      'vname' => 'LBL_CONSOLIDED_CONCEPT_VALUES',
      'type' => 'text',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '4',
      'cols' => '20',
      'id' => 'mks_RegistrationReceiptsconsolided_concept_values_c',
      'custom_module' => 'mks_RegistrationReceipts',
    ),
  ),
  'relationships' => 
  array (
    'mks_registrationreceipts_modified_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'mks_RegistrationReceipts',
      'rhs_table' => 'mks_registrationreceipts',
      'rhs_key' => 'modified_user_id',
      'relationship_type' => 'one-to-many',
    ),
    'mks_registrationreceipts_created_by' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'mks_RegistrationReceipts',
      'rhs_table' => 'mks_registrationreceipts',
      'rhs_key' => 'created_by',
      'relationship_type' => 'one-to-many',
    ),
    'mks_registrationreceipts_assigned_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'mks_RegistrationReceipts',
      'rhs_table' => 'mks_registrationreceipts',
      'rhs_key' => 'assigned_user_id',
      'relationship_type' => 'one-to-many',
    ),
    'securitygroups_mks_registrationreceipts' => 
    array (
      'lhs_module' => 'SecurityGroups',
      'lhs_table' => 'securitygroups',
      'lhs_key' => 'id',
      'rhs_module' => 'mks_RegistrationReceipts',
      'rhs_table' => 'mks_registrationreceipts',
      'rhs_key' => 'id',
      'relationship_type' => 'many-to-many',
      'join_table' => 'securitygroups_records',
      'join_key_lhs' => 'securitygroup_id',
      'join_key_rhs' => 'record_id',
      'relationship_role_column' => 'module',
      'relationship_role_column_value' => 'mks_RegistrationReceipts',
    ),
  ),
  'optimistic_locking' => true,
  'unified_search' => true,
  'indices' => 
  array (
    'id' => 
    array (
      'name' => 'mks_registrationreceiptspk',
      'type' => 'primary',
      'fields' => 
      array (
        0 => 'id',
      ),
    ),
  ),
  'templates' => 
  array (
    'security_groups' => 'security_groups',
    'assignable' => 'assignable',
    'basic' => 'basic',
  ),
  'custom_fields' => true,
);