<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2017 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */


$relationships = array (
  'mks_registration_mks_registrationreceipts_1' => 
  array (
    'id' => '11105c88-bfe0-2130-a5c9-5cf2b4f732d1',
    'relationship_name' => 'mks_registration_mks_registrationreceipts_1',
    'lhs_module' => 'mks_Registration',
    'lhs_table' => 'mks_registration',
    'lhs_key' => 'id',
    'rhs_module' => 'mks_RegistrationReceipts',
    'rhs_table' => 'mks_registrationreceipts',
    'rhs_key' => 'id',
    'join_table' => 'mks_registration_mks_registrationreceipts_1_c',
    'join_key_lhs' => 'mks_registration_mks_registrationreceipts_1mks_registration_ida',
    'join_key_rhs' => 'mks_regist608feceipts_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'mks_registrationreceipts_mks_paymentstransfer_1' => 
  array (
    'id' => '113470f3-f0af-80dd-0e05-5cf2b413c544',
    'relationship_name' => 'mks_registrationreceipts_mks_paymentstransfer_1',
    'lhs_module' => 'mks_RegistrationReceipts',
    'lhs_table' => 'mks_registrationreceipts',
    'lhs_key' => 'id',
    'rhs_module' => 'mks_PaymentsTransfer',
    'rhs_table' => 'mks_paymentstransfer',
    'rhs_key' => 'id',
    'join_table' => 'mks_registrationreceipts_mks_paymentstransfer_1_c',
    'join_key_lhs' => 'mks_regist09e2eceipts_ida',
    'join_key_rhs' => 'mks_regist887cransfer_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'mks_registrationreceipts_mks_paymentscard_1' => 
  array (
    'id' => '11696bf5-c737-2d96-5c58-5cf2b46e0a8c',
    'relationship_name' => 'mks_registrationreceipts_mks_paymentscard_1',
    'lhs_module' => 'mks_RegistrationReceipts',
    'lhs_table' => 'mks_registrationreceipts',
    'lhs_key' => 'id',
    'rhs_module' => 'mks_PaymentsCard',
    'rhs_table' => 'mks_paymentscard',
    'rhs_key' => 'id',
    'join_table' => 'mks_registrationreceipts_mks_paymentscard_1_c',
    'join_key_lhs' => 'mks_registfefbeceipts_ida',
    'join_key_rhs' => 'mks_registrationreceipts_mks_paymentscard_1mks_paymentscard_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'mks_registrationreceipts_mks_collectionconcepts_1' => 
  array (
    'id' => '13ce57c4-7afb-5c42-9933-5cf2b4a10696',
    'relationship_name' => 'mks_registrationreceipts_mks_collectionconcepts_1',
    'lhs_module' => 'mks_RegistrationReceipts',
    'lhs_table' => 'mks_registrationreceipts',
    'lhs_key' => 'id',
    'rhs_module' => 'mks_CollectionConcepts',
    'rhs_table' => 'mks_collectionconcepts',
    'rhs_key' => 'id',
    'join_table' => 'mks_registrationreceipts_mks_collectionconcepts_1_c',
    'join_key_lhs' => 'mks_regist10ebeceipts_ida',
    'join_key_rhs' => 'mks_registf2c4oncepts_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'mks_registrationreceipts_mks_paymentscash_1' => 
  array (
    'id' => '16740486-8c99-9cac-4fdd-5cf2b4f86a27',
    'relationship_name' => 'mks_registrationreceipts_mks_paymentscash_1',
    'lhs_module' => 'mks_RegistrationReceipts',
    'lhs_table' => 'mks_registrationreceipts',
    'lhs_key' => 'id',
    'rhs_module' => 'mks_PaymentsCash',
    'rhs_table' => 'mks_paymentscash',
    'rhs_key' => 'id',
    'join_table' => 'mks_registrationreceipts_mks_paymentscash_1_c',
    'join_key_lhs' => 'mks_regist1c49eceipts_ida',
    'join_key_rhs' => 'mks_registrationreceipts_mks_paymentscash_1mks_paymentscash_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'mks_registrationreceipts_mks_paymentscheck_1' => 
  array (
    'id' => '16b188d5-9cfe-1073-53f2-5cf2b4525189',
    'relationship_name' => 'mks_registrationreceipts_mks_paymentscheck_1',
    'lhs_module' => 'mks_RegistrationReceipts',
    'lhs_table' => 'mks_registrationreceipts',
    'lhs_key' => 'id',
    'rhs_module' => 'mks_PaymentsCheck',
    'rhs_table' => 'mks_paymentscheck',
    'rhs_key' => 'id',
    'join_table' => 'mks_registrationreceipts_mks_paymentscheck_1_c',
    'join_key_lhs' => 'mks_regista5a7eceipts_ida',
    'join_key_rhs' => 'mks_registf5b2tscheck_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'mks_custompaymentplan_mks_registrationreceipts_1' => 
  array (
    'id' => '16d42d76-76b9-3bf5-90b5-5cf2b474d8bd',
    'relationship_name' => 'mks_custompaymentplan_mks_registrationreceipts_1',
    'lhs_module' => 'mks_CustomPaymentPlan',
    'lhs_table' => 'mks_custompaymentplan',
    'lhs_key' => 'id',
    'rhs_module' => 'mks_RegistrationReceipts',
    'rhs_table' => 'mks_registrationreceipts',
    'rhs_key' => 'id',
    'join_table' => 'mks_custompaymentplan_mks_registrationreceipts_1_c',
    'join_key_lhs' => 'mks_custom8555entplan_ida',
    'join_key_rhs' => 'mks_custom1743eceipts_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'mks_registrationreceipts_modified_user' => 
  array (
    'id' => 'e5bc81cc-68e0-174a-87f3-5cf2b44a4749',
    'relationship_name' => 'mks_registrationreceipts_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'mks_RegistrationReceipts',
    'rhs_table' => 'mks_registrationreceipts',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'mks_registrationreceipts_created_by' => 
  array (
    'id' => 'e5e07124-6d99-8c4c-5240-5cf2b43a20e4',
    'relationship_name' => 'mks_registrationreceipts_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'mks_RegistrationReceipts',
    'rhs_table' => 'mks_registrationreceipts',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'mks_registrationreceipts_assigned_user' => 
  array (
    'id' => 'e6044c3c-6cbb-9c9d-f557-5cf2b4080f25',
    'relationship_name' => 'mks_registrationreceipts_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'mks_RegistrationReceipts',
    'rhs_table' => 'mks_registrationreceipts',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'securitygroups_mks_registrationreceipts' => 
  array (
    'id' => 'e62b8cbe-8302-7059-6e87-5cf2b4980b58',
    'relationship_name' => 'securitygroups_mks_registrationreceipts',
    'lhs_module' => 'SecurityGroups',
    'lhs_table' => 'securitygroups',
    'lhs_key' => 'id',
    'rhs_module' => 'mks_RegistrationReceipts',
    'rhs_table' => 'mks_registrationreceipts',
    'rhs_key' => 'id',
    'join_table' => 'securitygroups_records',
    'join_key_lhs' => 'securitygroup_id',
    'join_key_rhs' => 'record_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'module',
    'relationship_role_column_value' => 'mks_RegistrationReceipts',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => 'default',
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'mks_registrationreceipts_mks_customplanfees_1' => 
  array (
    'rhs_label' => 'Cuotas Pagadas',
    'lhs_label' => 'Recibos',
    'lhs_subpanel' => 'default',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'mks_RegistrationReceipts',
    'rhs_module' => 'mks_CustomPlanFees',
    'relationship_type' => 'many-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'mks_registrationreceipts_mks_customplanfees_1',
  ),
);