<?php 
 $GLOBALS["dictionary"]["mks_Registration"]=array (
  'table' => 'mks_registration',
  'audited' => true,
  'inline_edit' => true,
  'fields' => 
  array (
    'id' => 
    array (
      'name' => 'id',
      'vname' => 'LBL_ID',
      'type' => 'id',
      'required' => true,
      'reportable' => true,
      'comment' => 'Unique identifier',
      'inline_edit' => false,
    ),
    'name' => 
    array (
      'name' => 'name',
      'source' => 'non-db',
      'type' => 'varchar',
      'db_concat_fields' => 
      array (
        0 => 'document_name',
      ),
    ),
    'date_entered' => 
    array (
      'name' => 'date_entered',
      'vname' => 'LBL_DATE_ENTERED',
      'type' => 'datetime',
      'group' => 'created_by_name',
      'comment' => 'Date record created',
      'enable_range_search' => true,
      'options' => 'date_range_search_dom',
      'inline_edit' => false,
    ),
    'date_modified' => 
    array (
      'name' => 'date_modified',
      'vname' => 'LBL_DATE_MODIFIED',
      'type' => 'datetime',
      'group' => 'modified_by_name',
      'comment' => 'Date record last modified',
      'enable_range_search' => true,
      'options' => 'date_range_search_dom',
      'inline_edit' => false,
    ),
    'modified_user_id' => 
    array (
      'name' => 'modified_user_id',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_MODIFIED',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'group' => 'modified_by_name',
      'dbType' => 'id',
      'reportable' => true,
      'comment' => 'User who last modified record',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'modified_by_name' => 
    array (
      'name' => 'modified_by_name',
      'vname' => 'LBL_MODIFIED_NAME',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'rname' => 'user_name',
      'table' => 'users',
      'id_name' => 'modified_user_id',
      'module' => 'Users',
      'link' => 'modified_user_link',
      'duplicate_merge' => 'disabled',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'created_by' => 
    array (
      'name' => 'created_by',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_CREATED',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'dbType' => 'id',
      'group' => 'created_by_name',
      'comment' => 'User who created record',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'created_by_name' => 
    array (
      'name' => 'created_by_name',
      'vname' => 'LBL_CREATED',
      'type' => 'relate',
      'reportable' => false,
      'link' => 'created_by_link',
      'rname' => 'user_name',
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'created_by',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
      'importable' => 'false',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'description' => 
    array (
      'name' => 'description',
      'vname' => 'LBL_DESCRIPTION',
      'type' => 'text',
      'comment' => 'Full text of the note',
      'rows' => 6,
      'cols' => 80,
    ),
    'deleted' => 
    array (
      'name' => 'deleted',
      'vname' => 'LBL_DELETED',
      'type' => 'bool',
      'default' => '0',
      'reportable' => false,
      'comment' => 'Record deletion indicator',
    ),
    'created_by_link' => 
    array (
      'name' => 'created_by_link',
      'type' => 'link',
      'relationship' => 'mks_registration_created_by',
      'vname' => 'LBL_CREATED_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'modified_user_link' => 
    array (
      'name' => 'modified_user_link',
      'type' => 'link',
      'relationship' => 'mks_registration_modified_user',
      'vname' => 'LBL_MODIFIED_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'assigned_user_id' => 
    array (
      'name' => 'assigned_user_id',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'vname' => 'LBL_ASSIGNED_TO_ID',
      'group' => 'assigned_user_name',
      'type' => 'relate',
      'table' => 'users',
      'module' => 'Users',
      'reportable' => true,
      'isnull' => 'false',
      'dbType' => 'id',
      'audited' => true,
      'comment' => 'User ID assigned to record',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_name' => 
    array (
      'name' => 'assigned_user_name',
      'link' => 'assigned_user_link',
      'vname' => 'LBL_ASSIGNED_TO_NAME',
      'rname' => 'user_name',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'assigned_user_id',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_link' => 
    array (
      'name' => 'assigned_user_link',
      'type' => 'link',
      'relationship' => 'mks_registration_assigned_user',
      'vname' => 'LBL_ASSIGNED_TO_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
      'duplicate_merge' => 'enabled',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'table' => 'users',
    ),
    'SecurityGroups' => 
    array (
      'name' => 'SecurityGroups',
      'type' => 'link',
      'relationship' => 'securitygroups_mks_registration',
      'module' => 'SecurityGroups',
      'bean_name' => 'SecurityGroup',
      'source' => 'non-db',
      'vname' => 'LBL_SECURITYGROUPS',
    ),
    'document_name' => 
    array (
      'name' => 'document_name',
      'vname' => 'LBL_NAME',
      'type' => 'name',
      'link' => true,
      'dbType' => 'varchar',
      'len' => '255',
      'required' => true,
      'unified_search' => true,
      'full_text_search' => 
      array (
        'boost' => 3,
      ),
    ),
    'filename' => 
    array (
      'name' => 'filename',
      'vname' => 'LBL_FILENAME',
      'type' => 'varchar',
      'required' => true,
      'importable' => 'required',
      'len' => '255',
      'studio' => 'false',
    ),
    'file_ext' => 
    array (
      'name' => 'file_ext',
      'vname' => 'LBL_FILE_EXTENSION',
      'type' => 'varchar',
      'len' => 100,
    ),
    'file_mime_type' => 
    array (
      'name' => 'file_mime_type',
      'vname' => 'LBL_MIME',
      'type' => 'varchar',
      'len' => '100',
    ),
    'uploadfile' => 
    array (
      'name' => 'uploadfile',
      'vname' => 'LBL_FILE_UPLOAD',
      'type' => 'file',
      'source' => 'non-db',
    ),
    'active_date' => 
    array (
      'name' => 'active_date',
      'vname' => 'LBL_DOC_ACTIVE_DATE',
      'type' => 'date',
      'required' => false,
      'importable' => 'required',
      'display_default' => 'now',
      'inline_edit' => '',
      'merge_filter' => 'disabled',
      'enable_range_search' => false,
    ),
    'exp_date' => 
    array (
      'name' => 'exp_date',
      'vname' => 'LBL_DOC_EXP_DATE',
      'type' => 'date',
      'inline_edit' => '',
      'merge_filter' => 'disabled',
      'enable_range_search' => false,
    ),
    'category_id' => 
    array (
      'name' => 'category_id',
      'vname' => 'LBL_SF_CATEGORY',
      'type' => 'enum',
      'len' => 100,
      'options' => 'document_category_dom',
      'reportable' => true,
      'inline_edit' => '',
      'merge_filter' => 'disabled',
    ),
    'subcategory_id' => 
    array (
      'name' => 'subcategory_id',
      'vname' => 'LBL_SF_SUBCATEGORY',
      'type' => 'enum',
      'len' => 100,
      'options' => 'document_subcategory_dom',
      'reportable' => true,
      'inline_edit' => '',
      'merge_filter' => 'disabled',
    ),
    'status_id' => 
    array (
      'name' => 'status_id',
      'vname' => 'LBL_DOC_STATUS',
      'type' => 'enum',
      'len' => 100,
      'options' => 'document_status_dom',
      'reportable' => true,
      'default' => 'Draft',
      'inline_edit' => '',
      'merge_filter' => 'disabled',
    ),
    'status' => 
    array (
      'name' => 'status',
      'vname' => 'LBL_DOC_STATUS',
      'type' => 'varchar',
      'source' => 'non-db',
      'Comment' => 'Document status for Meta-Data framework',
    ),
    'opportunity_id_c' => 
    array (
      'required' => false,
      'name' => 'opportunity_id_c',
      'vname' => 'LBL_OPPORTUNITY_OPPORTUNITY_ID',
      'type' => 'id',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'inline_edit' => true,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 36,
      'size' => '20',
    ),
    'opportunity' => 
    array (
      'required' => true,
      'source' => 'non-db',
      'name' => 'opportunity',
      'vname' => 'LBL_OPPORTUNITY',
      'type' => 'relate',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'opportunity_id_c',
      'ext2' => 'Opportunities',
      'module' => 'Opportunities',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
    ),
    'mks_courses_id_c' => 
    array (
      'required' => false,
      'name' => 'mks_courses_id_c',
      'vname' => 'LBL_COURSE_MKS_COURSES_ID',
      'type' => 'id',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'inline_edit' => true,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 36,
      'size' => '20',
    ),
    'course' => 
    array (
      'required' => true,
      'source' => 'non-db',
      'name' => 'course',
      'vname' => 'LBL_COURSE',
      'type' => 'relate',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'mks_courses_id_c',
      'ext2' => 'mks_Courses',
      'module' => 'mks_Courses',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
    ),
    'mks_academicgroups_id_c' => 
    array (
      'required' => false,
      'name' => 'mks_academicgroups_id_c',
      'vname' => 'LBL_GROUPTHEORY_MKS_ACADEMICGROUPS_ID',
      'type' => 'id',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'inline_edit' => true,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 36,
      'size' => '20',
    ),
    'grouptheory' => 
    array (
      'required' => false,
      'source' => 'non-db',
      'name' => 'grouptheory',
      'vname' => 'LBL_GROUPTHEORY',
      'type' => 'relate',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'mks_academicgroups_id_c',
      'ext2' => 'mks_AcademicGroups',
      'module' => 'mks_AcademicGroups',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
    ),
    'mks_academicgroups_id1_c' => 
    array (
      'required' => false,
      'name' => 'mks_academicgroups_id1_c',
      'vname' => 'LBL_GROUPPRACTICE_MKS_ACADEMICGROUPS_ID',
      'type' => 'id',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'inline_edit' => true,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 36,
      'size' => '20',
    ),
    'grouppractice' => 
    array (
      'required' => false,
      'source' => 'non-db',
      'name' => 'grouppractice',
      'vname' => 'LBL_GROUPPRACTICE',
      'type' => 'relate',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'mks_academicgroups_id1_c',
      'ext2' => 'mks_AcademicGroups',
      'module' => 'mks_AcademicGroups',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
    ),
    'first_expiration' => 
    array (
      'required' => false,
      'name' => 'first_expiration',
      'vname' => 'LBL_ FIRST_EXPIRATION',
      'type' => 'date',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
    ),
    'second_expiration' => 
    array (
      'required' => false,
      'name' => 'second_expiration',
      'vname' => 'LBL_SECOND_EXPIRATION',
      'type' => 'date',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
    ),
    'size' => 
    array (
      'required' => false,
      'name' => 'size',
      'vname' => 'LBL_SIZE',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'size_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'photo' => 
    array (
      'required' => false,
      'name' => 'photo',
      'vname' => 'LBL_PHOTO',
      'type' => 'image',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'inline_edit' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 255,
      'size' => '20',
      'studio' => 'visible',
      'dbType' => 'varchar',
      'border' => '1',
      'width' => '120',
      'height' => '',
    ),
    'id_autoincrement' => 
    array (
      'required' => false,
      'name' => 'id_autoincrement',
      'vname' => 'LBL_ID_AUTOINCREMENT',
      'type' => 'autoincrement',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 80,
      'size' => '20',
      'dbType' => 'varchar',
      'format' => '{MT}{-}{y}{-}{00000000}{}{}',
      'start_number' => '00001',
    ),
    'mks_paymentplan_id_c' => 
    array (
      'required' => false,
      'name' => 'mks_paymentplan_id_c',
      'vname' => 'LBL_PAYMENTPLAN_MKS_PAYMENTPLAN_ID',
      'type' => 'id',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => false,
      'inline_edit' => true,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 36,
      'size' => '20',
    ),
    'paymentplan' => 
    array (
      'required' => false,
      'source' => 'non-db',
      'name' => 'paymentplan',
      'vname' => 'LBL_PAYMENTPLAN',
      'type' => 'relate',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'inline_edit' => '',
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'mks_paymentplan_id_c',
      'ext2' => 'mks_PaymentPlan',
      'module' => 'mks_PaymentPlan',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
    ),
    'mks_registration_contacts' => 
    array (
      'name' => 'mks_registration_contacts',
      'type' => 'link',
      'relationship' => 'mks_registration_contacts',
      'source' => 'non-db',
      'module' => 'Contacts',
      'bean_name' => 'Contact',
      'vname' => 'LBL_MKS_REGISTRATION_CONTACTS_FROM_CONTACTS_TITLE',
      'id_name' => 'mks_registration_contactscontacts_ida',
    ),
    'mks_registration_contacts_name' => 
    array (
      'name' => 'mks_registration_contacts_name',
      'type' => 'relate',
      'source' => 'non-db',
      'vname' => 'LBL_MKS_REGISTRATION_CONTACTS_FROM_CONTACTS_TITLE',
      'save' => true,
      'id_name' => 'mks_registration_contactscontacts_ida',
      'link' => 'mks_registration_contacts',
      'table' => 'contacts',
      'module' => 'Contacts',
      'rname' => 'name',
      'db_concat_fields' => 
      array (
        0 => 'first_name',
        1 => 'last_name',
      ),
    ),
    'mks_registration_contactscontacts_ida' => 
    array (
      'name' => 'mks_registration_contactscontacts_ida',
      'type' => 'link',
      'relationship' => 'mks_registration_contacts',
      'source' => 'non-db',
      'reportable' => false,
      'side' => 'right',
      'vname' => 'LBL_MKS_REGISTRATION_CONTACTS_FROM_MKS_REGISTRATION_TITLE',
    ),
    'mks_custompaymentplan_mks_registration' => 
    array (
      'name' => 'mks_custompaymentplan_mks_registration',
      'type' => 'link',
      'relationship' => 'mks_custompaymentplan_mks_registration',
      'source' => 'non-db',
      'module' => 'mks_CustomPaymentPlan',
      'bean_name' => 'mks_CustomPaymentPlan',
      'side' => 'right',
      'vname' => 'LBL_MKS_CUSTOMPAYMENTPLAN_MKS_REGISTRATION_FROM_MKS_CUSTOMPAYMENTPLAN_TITLE',
    ),
    'flag_payment_plan_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Bandera Plan de Pago',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'flag_payment_plan_c',
      'vname' => 'LBL_FLAG_PAYMENT_PLAN',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '0',
      'no_default' => false,
      'comments' => 'Indica si se replicaron las cuotas y reglas del pago.',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '1',
      'size' => '20',
      'id' => 'mks_Registrationflag_payment_plan_c',
      'custom_module' => 'mks_Registration',
    ),
    'accounts_mks_registration_1' => 
    array (
      'name' => 'accounts_mks_registration_1',
      'type' => 'link',
      'relationship' => 'accounts_mks_registration_1',
      'source' => 'non-db',
      'module' => 'Accounts',
      'bean_name' => 'Account',
      'vname' => 'LBL_ACCOUNTS_MKS_REGISTRATION_1_FROM_ACCOUNTS_TITLE',
      'id_name' => 'accounts_mks_registration_1accounts_ida',
    ),
    'accounts_mks_registration_1_name' => 
    array (
      'name' => 'accounts_mks_registration_1_name',
      'type' => 'relate',
      'source' => 'non-db',
      'vname' => 'LBL_ACCOUNTS_MKS_REGISTRATION_1_FROM_ACCOUNTS_TITLE',
      'save' => true,
      'id_name' => 'accounts_mks_registration_1accounts_ida',
      'link' => 'accounts_mks_registration_1',
      'table' => 'accounts',
      'module' => 'Accounts',
      'rname' => 'name',
    ),
    'accounts_mks_registration_1accounts_ida' => 
    array (
      'name' => 'accounts_mks_registration_1accounts_ida',
      'type' => 'link',
      'relationship' => 'accounts_mks_registration_1',
      'source' => 'non-db',
      'reportable' => false,
      'side' => 'right',
      'vname' => 'LBL_ACCOUNTS_MKS_REGISTRATION_1_FROM_MKS_REGISTRATION_TITLE',
    ),
    'mks_registration_securitygroups_1' => 
    array (
      'name' => 'mks_registration_securitygroups_1',
      'type' => 'link',
      'relationship' => 'mks_registration_securitygroups_1',
      'source' => 'non-db',
      'module' => 'SecurityGroups',
      'bean_name' => 'SecurityGroup',
      'vname' => 'LBL_MKS_REGISTRATION_SECURITYGROUPS_1_FROM_SECURITYGROUPS_TITLE',
    ),
    'reg_num_c' => 
    array (
      'inline_edit' => '',
      'labelValue' => 'Matricula N°',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'reg_num_c',
      'vname' => 'LBL_REG_NUM',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'mks_Registrationreg_num_c',
      'custom_module' => 'mks_Registration',
    ),
    'debt_c' => 
    array (
      'inline_edit' => '',
      'labelValue' => 'Deduda cuota vencida',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'debt_c',
      'vname' => 'LBL_DEBT',
      'type' => 'float',
      'massupdate' => '0',
      'default' => '0.00',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '10',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '2',
      'id' => 'mks_Registrationdebt_c',
      'custom_module' => 'mks_Registration',
    ),
    'surcharge_c' => 
    array (
      'inline_edit' => '',
      'labelValue' => 'Recargo %',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'surcharge_c',
      'vname' => 'LBL_SURCHARGE',
      'type' => 'float',
      'massupdate' => '0',
      'default' => '0.00',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '2',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '2',
      'id' => 'mks_Registrationsurcharge_c',
      'custom_module' => 'mks_Registration',
    ),
    'discount_c' => 
    array (
      'inline_edit' => '',
      'labelValue' => 'Mondo del Descuento',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'discount_c',
      'vname' => 'LBL_DISCOUNT',
      'type' => 'float',
      'massupdate' => '0',
      'default' => '0.00',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '10',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '2',
      'id' => 'mks_Registrationdiscount_c',
      'custom_module' => 'mks_Registration',
    ),
    'total_debt_c' => 
    array (
      'inline_edit' => '',
      'labelValue' => 'Deuda total del plan',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'total_debt_c',
      'vname' => 'LBL_ TOTAL_DEBT',
      'type' => 'float',
      'massupdate' => '0',
      'default' => '0.00',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '10',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '2',
      'id' => 'mks_Registrationtotal_debt_c',
      'custom_module' => 'mks_Registration',
    ),
    'mks_refinances_mks_registration' => 
    array (
      'name' => 'mks_refinances_mks_registration',
      'type' => 'link',
      'relationship' => 'mks_refinances_mks_registration',
      'source' => 'non-db',
      'module' => 'mks_Refinances',
      'bean_name' => 'mks_Refinances',
      'side' => 'right',
      'vname' => 'LBL_MKS_REFINANCES_MKS_REGISTRATION_FROM_MKS_REFINANCES_TITLE',
    ),
    'mks_registration_id_c' => 
    array (
      'inline_edit' => 1,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'mks_registration_id_c',
      'vname' => 'LBL_REGISTER_MKS_REGISTRATION_ID',
      'type' => 'id',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '36',
      'size' => '20',
      'id' => 'mks_Registrationmks_registration_id_c',
      'custom_module' => 'mks_Registration',
    ),
    'register_c' => 
    array (
      'inline_edit' => '',
      'labelValue' => 'Matricula Asociada',
      'required' => false,
      'source' => 'non-db',
      'name' => 'register_c',
      'vname' => 'LBL_REGISTER',
      'type' => 'relate',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id_name' => 'mks_registration_id_c',
      'ext2' => 'mks_Registration',
      'module' => 'mks_Registration',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
      'id' => 'mks_Registrationregister_c',
      'custom_module' => 'mks_Registration',
    ),
    'amount_fees_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => '# Cuotas',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'amount_fees_c',
      'vname' => 'LBL_AMOUNT_FEES_C',
      'type' => 'enum',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'amount_fees_list',
      'studio' => 'visible',
      'dependency' => false,
      'id' => 'mks_Registrationamount_fees_c',
      'custom_module' => 'mks_Registration',
    ),
    'advance_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Anticipo',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'advance_c',
      'vname' => 'LBL_ADVANCE_C',
      'type' => 'float',
      'massupdate' => '0',
      'default' => '0.00',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '11',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '2',
      'id' => 'mks_Registrationadvance_c',
      'custom_module' => 'mks_Registration',
    ),
    'mks_registration_mks_registrationreceipts_1' => 
    array (
      'name' => 'mks_registration_mks_registrationreceipts_1',
      'type' => 'link',
      'relationship' => 'mks_registration_mks_registrationreceipts_1',
      'source' => 'non-db',
      'module' => 'mks_RegistrationReceipts',
      'bean_name' => 'mks_RegistrationReceipts',
      'side' => 'right',
      'vname' => 'LBL_MKS_REGISTRATION_MKS_REGISTRATIONRECEIPTS_1_FROM_MKS_REGISTRATIONRECEIPTS_TITLE',
    ),
    'mks_registration_mks_management_1' => 
    array (
      'name' => 'mks_registration_mks_management_1',
      'type' => 'link',
      'relationship' => 'mks_registration_mks_management_1',
      'source' => 'non-db',
      'module' => 'mks_Management',
      'bean_name' => 'mks_Management',
      'side' => 'right',
      'vname' => 'LBL_MKS_REGISTRATION_MKS_MANAGEMENT_1_FROM_MKS_MANAGEMENT_TITLE',
    ),
  ),
  'relationships' => 
  array (
    'mks_registration_modified_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'mks_Registration',
      'rhs_table' => 'mks_registration',
      'rhs_key' => 'modified_user_id',
      'relationship_type' => 'one-to-many',
    ),
    'mks_registration_created_by' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'mks_Registration',
      'rhs_table' => 'mks_registration',
      'rhs_key' => 'created_by',
      'relationship_type' => 'one-to-many',
    ),
    'mks_registration_assigned_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'mks_Registration',
      'rhs_table' => 'mks_registration',
      'rhs_key' => 'assigned_user_id',
      'relationship_type' => 'one-to-many',
    ),
    'securitygroups_mks_registration' => 
    array (
      'lhs_module' => 'SecurityGroups',
      'lhs_table' => 'securitygroups',
      'lhs_key' => 'id',
      'rhs_module' => 'mks_Registration',
      'rhs_table' => 'mks_registration',
      'rhs_key' => 'id',
      'relationship_type' => 'many-to-many',
      'join_table' => 'securitygroups_records',
      'join_key_lhs' => 'securitygroup_id',
      'join_key_rhs' => 'record_id',
      'relationship_role_column' => 'module',
      'relationship_role_column_value' => 'mks_Registration',
    ),
  ),
  'optimistic_locking' => true,
  'unified_search' => true,
  'indices' => 
  array (
    'id' => 
    array (
      'name' => 'mks_registrationpk',
      'type' => 'primary',
      'fields' => 
      array (
        0 => 'id',
      ),
    ),
  ),
  'templates' => 
  array (
    'file' => 'file',
    'security_groups' => 'security_groups',
    'assignable' => 'assignable',
    'basic' => 'basic',
  ),
  'custom_fields' => true,
);